In [11]:
import numpy as np
import pandas as pd

## Series

1-dim data structure (similar to numpy arrays). Major difference is in the access pattern: it allows access based on _lebels_ not just positions.

In [3]:
labels = ['l1', 'l2', 'l3']
data = [10, 20, 30]

You can create a series directly from raw data (pyhton lists or np arrays), and the index will be automatically generated (as integers).

In [4]:
series = pd.Series(data)
print(series)

# access is positional in this case just like for np arrays
series[0]

0    10
1    20
2    30
dtype: int64

np.int64(10)

But you can also explicitly set the labels (i.e. the so-called `Index`).

In [5]:
series = pd.Series(data=data, index=labels)
print(series)

# access is now label-based
series['l1']

l1    10
l2    20
l3    30
dtype: int64

np.int64(10)

You can create a labeles series directly from a Python dictionary.

In [6]:
data = { 'l1': 10, 'l2': 20, 'l3': 30}
series = pd.Series(data)

print(series)

l1    10
l2    20
l3    30
dtype: int64

You can hold any type of object as values in a series (even function objects).

In [7]:
series = pd.Series(data=[0, "one", print])
print(series)

0                            0
1                          one
2    <built-in function print>
dtype: object

Operations involving multiple series are "label aligned": where labels don't match il will put null (NaN in the example below).

In [8]:
s1 = pd.Series({"a": 1, "b": 2})
s2 = pd.Series({"a": 1, "c": 3})
s3 = s1 + s2

print(s3)

a    2.0
b    NaN
c    NaN
dtype: float64

The presence of `NaN` causes the `s3` series above to be upcast to `float64`; `int` series cannot hold `NaN`s, but `Int64` can (use `.astype` to perform type casting):

In [9]:
print(s3.astype('Int64'))

a       2
b    <NA>
c    <NA>
dtype: Int64

## DataFrame's

A `DataFrame` is a 2D data structures with columns and rows (row labels). Think of it as an excel table. Technically, a DataFrame is a set of series (columns) sharing the same row labels (indexes).

In [13]:
df = pd.DataFrame(
    data=np.random.randn(5, 4), # 5 rows and 4 cols
    index=["A", "B", "C", "D", "E"], # row labels
    columns=["X", "Y", "Z", "W"] # col labels
)

display(df)

          X         Y         Z         W
A  0.270635  0.481220  0.777240  1.093384
B -1.597841  0.339844 -0.777960 -0.551361
C  1.008118 -0.193663  0.942528  1.085865
D  0.048902 -0.620732  0.461518  1.214627
E  1.520871  0.382640  0.540978 -0.432469

Selecting individual columns gives us the corresponding pandas series:

In [14]:
display(df["X"])

A    0.270635
B   -1.597841
C    1.008118
D    0.048902
E    1.520871
Name: X, dtype: float64

One can selects multiple cols at the same time (the result will be another data-frame) by passing a **list** of column names as the value of the index into the original data-frame:

In [15]:
display(df[["X", "Y"]])

          X         Y
A  0.270635  0.481220
B -1.597841  0.339844
C  1.008118 -0.193663
D  0.048902 -0.620732
E  1.520871  0.382640

Creating a new column:

In [19]:
df["T"] = df["X"] + df["Y"]

display(df)

          X         Y         Z         W         T
A  0.270635  0.481220  0.777240  1.093384  0.751855
B -1.597841  0.339844 -0.777960 -0.551361 -1.257998
C  1.008118 -0.193663  0.942528  1.085865  0.814455
D  0.048902 -0.620732  0.461518  1.214627 -0.571830
E  1.520871  0.382640  0.540978 -0.432469  1.903512

You can delete columns (returns a **new** data-frame - unless you pass in `inplace=True`).

**NOTE**: using `inplace=True` is _strongly discouraged_ in recent versions of pandas - use explicit reassignment of the data-frame instead.

In [ ]:
display(df.drop(columns="T"))

# same as:
# df.drop("T", axis=1)

          X         Y         Z         W
A  0.270635  0.481220  0.777240  1.093384
B -1.597841  0.339844 -0.777960 -0.551361
C  1.008118 -0.193663  0.942528  1.085865
D  0.048902 -0.620732  0.461518  1.214627
E  1.520871  0.382640  0.540978 -0.432469

You can delete **rows** in a similar fashion:

In [24]:
display(df.drop("A"))

# same as
# df.drop("A", axis=0)

          X         Y         Z         W         T
B -1.597841  0.339844 -0.777960 -0.551361 -1.257998
C  1.008118 -0.193663  0.942528  1.085865  0.814455
D  0.048902 -0.620732  0.461518  1.214627 -0.571830
E  1.520871  0.382640  0.540978 -0.432469  1.903512

Data-frames use numpy arrays under the hood:

In [25]:
df.shape

(5, 5)

Selecting rows can be done by label or by position:

In [29]:
display(df.loc["A"]) # this gives you back a series

display(df.loc[["A"]]) # this gives you back a data-frame instead

X    0.270635
Y    0.481220
Z    0.777240
W    1.093384
T    0.751855
Name: A, dtype: float64

          X        Y        Z         W         T
A  0.270635  0.48122  0.77724  1.093384  0.751855

In [32]:
display(df.iloc[0])
display(df.iloc[[0, 1]])

X    0.270635
Y    0.481220
Z    0.777240
W    1.093384
T    0.751855
Name: A, dtype: float64

          X         Y        Z         W         T
A  0.270635  0.481220  0.77724  1.093384  0.751855
B -1.597841  0.339844 -0.77796 -0.551361 -1.257998

Selecting a **single or multiple cell**:

In [36]:
display(df.loc["A", "Y"])
display(df.loc[["A", "B"], ["Y", "W"]])

np.float64(0.48122004891244)

          Y         W
A  0.481220  1.093384
B  0.339844 -0.551361